title: Sam Tauke # your name (or website title) here
logo: "https://github.com/samtauke/samtauke.github.io/blob/main/images/id_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS: Statistics, Data Science Candidate at the University of Wisconsin-Madison 
  <br><br>
  I will be graduating this summer and am looking for full-time data science positions starting in August 2021.  
  <br><br>
  <a href="https://www.linkedin.com/in/samtauke/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
