title: Sam Tauke # your name (or website title) here
logo: "https://github.com/samtauke/samtauke.github.io/blob/main/images/id_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS: Statistics, Data Science Candidate at the University of Wisconsin-Madison 
  <br><br>
  After graduating from Middlebury College with a double major in Math and Economics, I went to work as an analyst at Cornerstone Research.  Over four years and many different projects, I learned how to  work effectively and efficiently on teams in a data-driven driven environment.  We used R, SAS, and Excel to compile reports supporting expert testimony in all manners of complex financial litigation.  
  
  Having found a passion for using data to inform decisions, I went back to school for MS in Statistics and Data Science.  Through my coursework, I have established a strong foundation in both the theoretical concepts and practical applications necessary to succeed as a professional data scientist.  I have had extensive experience using Python and Bash along the full life-cycle of analytics projects. 
  
  I will be graduating this summer and am looking for full-time data science positions starting in August 2021.  
  <br><br>
  <a href="https://www.linkedin.com/in/samtauke/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
